version: "3.8"

services:
  app:
    image: nginx:alpine
    container_name: lab6_app
    networks:
      - lab_net

  proxy:
    image: nginx:alpine
    container_name: lab6_proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - lab_net

networks:
  lab_net:
    driver: bridge